---
title: "Project 2"
author: "Nicholas Philo"
date: "27/07/2020"
output: rmarkdown::github_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Downloading the data

```{r}
library(tidyr)
```


```{r}
dta_url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip"
download.file(dta_url , destfile = "unzipme.zip", method = "curl")
unzip("unzipme.zip")
```
## Reading in the data
```{r}
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
```

now investigating the data:
```{r}
str(NEI)
str(SCC)
```

```{r}
NEI$fips <- as.factor(NEI$fips)
NEI$Pollutant <- as.factor(NEI$Pollutant)
NEI$type <- as.factor(NEI$type)

length(levels(NEI$fips))


year_test <- levels(as.factor(NEI$year))
year_test

```

```{r}
head(NEI)
```

```{r}




f1 <- function(yr){
    subset(NEI, year == yr)
}


YEARS <- lapply(year_test,f1)


f2 <- function(dta_list){
    sum(dta_list$Emissions)
}

tot_em <- sapply(YEARS,f2)

barplot(tot_em ~ year_test, xlab = "Years",ylab = "Emissions" ,main = "Total US Emmisions in 1999, 2002, 2005 & 2008", col = "wheat", space = 0.1, border = NA, axes = TRUE, ylim = c(  0,max(tot_em)*1.1  )  )


```


```{r}
cond_baltimore <- which(as.character(NEI$fips) == "24510")
balt <- NEI[cond_baltimore,]

fa <- function(yr){
    subset(balt, year == yr)
}

baltyr <- lapply(year_test,fa)

fb <- function(dta_list){
    sum(dta_list$Emissions)
}

baltemmisions <- sapply(baltyr,fb)

barplot(baltemmisions~year_test)

```

